package constants

var (
	SUCCESS = 200
	CREATED        = 201
	// ACCEPTED_STATUS      = 202
	// NOCONTENT            = 204
	BADREQUEST   = 400
	UNAUTHORIZED = 401
	FORBIDDEN    = 403
	NOTFOUND     = 404
	// METHODNOTALLOWED     = 405
	CONFLICT = 409
	// PRECONDITIONFAILED   = 412
	// UNSUPPORTEDMEDIATYPE = 415
	// UNPROCESSABLEENTITY  = 422
	INTERNALSERVERERROR = 500
	// NOTIMPLEMENTED       = 501
	// BADGATEWAY           = 502
	// SERVICEUNAVAILABLE   = 503
	// GATEWAYTIMEOUT       = 504

	// Generic Status Strings
	PENDING = "PENDING"
	// COMPLETED       = "COMPLETED"
	// APPROVED        = "APPROVED"
	// ACCEPTED        = "ACCEPTED"
	// REJECTED        = "REJECTED"
	INVALID_REQUEST = "INVALID_REQUEST"
	UN_AUTHORIZED   = "UNAUTHORIZED"
	INTERNAL_ERROR  = "INTERNAL_ERROR"
	PAID            = "PAID"
	FAILED          = "FAILED"

	// Transaction Types
	// DEPOSIT  = "DEPOSIT"
	// SPEND    = "SPEND"
	// WITHDRAW = "WITHDRAW"

	// Optional: Payment or process states
	// PROCESSING = "PROCESSING"
	CANCELLED = "CANCELLED"
	PLACED    = "PLACED"
	SHIPPED   = "SHIPPED"
	DELIVERED = "DELIVERED"
)
